# Generated by Django 5.2.1 on 2025-05-13 06:04

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('template_type', models.CharField(choices=[('gost', 'ГОСТ 7.32'), ('sto', 'СТО СФУ 4.2')], max_length=10)),
                ('report_type', models.CharField(choices=[('final', 'Заключительный'), ('intermediate', 'Промежуточный')], default=('intermediate', 'Промежуточный'), max_length=20)),
                ('year', models.PositiveIntegerField(default=2024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('introduction', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('main_part', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('conclusion', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appendix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('order', models.PositiveIntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appendices', to='documents.document')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abstract', to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='Abbreviation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=100)),
                ('meaning', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abbreviations', to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='Document_sto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('MAG_DIPLOMA', 'Магистерская диссертация'), ('DIPLOMA', 'Дипломная работа/проект'), ('BACHELOR', 'Бакалаврская работа'), ('COURSE', 'Курсовой проект/работа'), ('CALC_GRAPH', 'Расчётно-графическая работа'), ('PRACTICE', 'Отчёт по практике'), ('LAB', 'Отчёт по лабораторной работе'), ('REF', 'Реферат')], max_length=20, verbose_name='Вид работы')),
                ('specialty_code', models.CharField(blank=True, max_length=20, verbose_name='Код специальности')),
                ('specialty_name', models.CharField(blank=True, max_length=200, verbose_name='Наименование специальности/направления')),
                ('title', models.CharField(max_length=255, verbose_name='Тема работы')),
                ('supervisor', models.CharField(max_length=200, verbose_name='Руководитель (ФИО, ученая степень/звание)')),
                ('student_name', models.CharField(max_length=200, verbose_name='Исполнитель (ФИО)')),
                ('consultants', models.TextField(blank=True, help_text='По пункту 6.2.2: консультанты и нормоконтролёр', verbose_name='Консультанты (ФИО, должность)')),
                ('approval_note', models.CharField(blank=True, help_text='Заполняется для ВКР и отчётов', max_length=200, verbose_name='Гриф утверждения')),
                ('city', models.CharField(default='Бишкек', max_length=100, verbose_name='Город выполнения')),
                ('year', models.PositiveSmallIntegerField(default=2025, verbose_name='Год выполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Документ СТО',
                'verbose_name_plural': 'Документы СТО',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BibliographyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Порядок в списке')),
                ('entry_text', models.TextField(verbose_name='Оформление по ГОСТ 7.1–2003')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biblio', to='documents.document_sto')),
            ],
            options={
                'verbose_name': 'Элемент списка источников СТО',
                'verbose_name_plural': 'Список использованных источников СТО',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Appendix_sto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=2, verbose_name='Буквенный индекс (Приложение А, Б, …)')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название приложения')),
                ('content', models.FileField(upload_to='appendices/', verbose_name='Файл приложения')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appendices', to='documents.document_sto')),
            ],
            options={
                'verbose_name': 'Приложение СТО',
                'verbose_name_plural': 'Приложения СТО',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Abstract_sto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_count', models.PositiveSmallIntegerField(verbose_name='Кол-во страниц')),
                ('illustrations_count', models.PositiveSmallIntegerField(verbose_name='Кол-во иллюстраций')),
                ('tables_count', models.PositiveSmallIntegerField(verbose_name='Кол-во таблиц')),
                ('formulas_count', models.PositiveSmallIntegerField(verbose_name='Кол-во формул')),
                ('appendices_count', models.PositiveSmallIntegerField(verbose_name='Кол-во приложений')),
                ('references_count', models.PositiveSmallIntegerField(verbose_name='Кол-во источников')),
                ('graphic_sheets', models.PositiveSmallIntegerField(verbose_name='Листов графического материала')),
                ('keywords', models.TextField(help_text='До 15 слов/словосочетаний, прописными, через запятую', verbose_name='Ключевые слова')),
                ('text', models.TextField(verbose_name='Текст реферата')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abstract', to='documents.document_sto')),
            ],
            options={
                'verbose_name': 'Реферат СТО',
                'verbose_name_plural': 'Рефераты СТО',
                'ordering': ['document__created_at'],
            },
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=100)),
                ('participation', models.CharField(blank=True, max_length=500)),
                ('signed', models.BooleanField(default=False)),
                ('date_signed', models.DateField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performers', to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='documents.document')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INTRO', 'Введение'), ('MAIN', 'Основная часть'), ('CONCL', 'Заключение')], max_length=5, verbose_name='Тип раздела')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Порядок')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок раздела')),
                ('content', models.TextField(verbose_name='Содержимое (HTML или текст)')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='documents.document_sto')),
            ],
            options={
                'verbose_name': 'Раздел СТО',
                'verbose_name_plural': 'Разделы СТО',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='TitlePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(blank=True, max_length=255)),
                ('udk', models.CharField(blank=True, max_length=50)),
                ('registration_number_nioktr', models.CharField(blank=True, max_length=100)),
                ('registration_number_ikrbs', models.CharField(blank=True, max_length=100)),
                ('program_code', models.CharField(blank=True, max_length=255)),
                ('book_number', models.CharField(blank=True, max_length=20)),
                ('federal_program_name', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('head_full_name', models.CharField(blank=True, max_length=255)),
                ('head_position', models.CharField(blank=True, max_length=255)),
                ('head_degree', models.CharField(blank=True, max_length=100)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='title_page', to='documents.document')),
            ],
        ),
    ]
