# Generated by Django 5.2.1 on 2025-05-12 07:21

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('template_type', models.CharField(choices=[('gost', 'ГОСТ 7.32'), ('sto', 'СТО СФУ 4.2')], max_length=10)),
                ('introduction', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('goal', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('tasks', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('main_part', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('conclusion', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('year', models.PositiveIntegerField(default=2024)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('doc_type', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
