# Generated by Django 5.2.1 on 2025-05-12 15:56

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='author',
        ),
        migrations.RemoveField(
            model_name='document',
            name='department',
        ),
        migrations.RemoveField(
            model_name='document',
            name='doc_type',
        ),
        migrations.RemoveField(
            model_name='document',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='document',
            name='tasks',
        ),
        migrations.AddField(
            model_name='document',
            name='report_type',
            field=models.CharField(choices=[('final', 'Заключительный'), ('intermediate', 'Промежуточный')], default=('intermediate', 'Промежуточный'), max_length=20),
        ),
        migrations.CreateModel(
            name='Abbreviation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=100)),
                ('meaning', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abbreviations', to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abstract', to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='Appendix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('order', models.PositiveIntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appendices', to='documents.document')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=100)),
                ('participation', models.CharField(blank=True, max_length=500)),
                ('signed', models.BooleanField(default=False)),
                ('date_signed', models.DateField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performers', to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='documents.document')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='TitlePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(blank=True, max_length=255)),
                ('udk', models.CharField(blank=True, max_length=50)),
                ('registration_number_nioktr', models.CharField(blank=True, max_length=100)),
                ('registration_number_ikrbs', models.CharField(blank=True, max_length=100)),
                ('program_code', models.CharField(blank=True, max_length=255)),
                ('book_number', models.CharField(blank=True, max_length=20)),
                ('federal_program_name', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('head_full_name', models.CharField(blank=True, max_length=255)),
                ('head_position', models.CharField(blank=True, max_length=255)),
                ('head_degree', models.CharField(blank=True, max_length=100)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='title_page', to='documents.document')),
            ],
        ),
    ]
