# Generated by Django 5.2.1 on 2025-05-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_main',
            name='references_doi',
            field=models.TextField(blank=True, help_text='Введите DOI источников через запятую, например: 10.1000/xyz123, 10.1000/abc456', null=True, verbose_name='DOI источников (через запятую)'),
        ),
    ]
