# Generated by Django 5.2.1 on 2025-05-13 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at'], 'verbose_name': 'Документ ГОСТ', 'verbose_name_plural': 'Документы ГОСТ'},
        ),
    ]
