# Generated by Django 5.2.1 on 2025-05-13 15:18

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appendix',
            options={'ordering': ['order'], 'verbose_name': 'Приложение', 'verbose_name_plural': 'Приложения'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at'], 'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='reference',
            options={'ordering': ['order'], 'verbose_name': 'Источник', 'verbose_name_plural': 'Список источников'},
        ),
        migrations.AlterField(
            model_name='abbreviation',
            name='abbreviation',
            field=models.CharField(max_length=100, verbose_name='Сокращение'),
        ),
        migrations.AlterField(
            model_name='abbreviation',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abbreviations', to='documents.document', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='abbreviation',
            name='meaning',
            field=models.TextField(verbose_name='Расшифровка'),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержание реферата'),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abstract', to='documents.document', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='abstract_sto',
            name='keywords',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='До 15 слов/словосочетаний, прописными, через запятую', verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='abstract_sto',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст реферата'),
        ),
        migrations.AlterField(
            model_name='appendix',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержание приложения'),
        ),
        migrations.AlterField(
            model_name='appendix',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appendices', to='documents.document', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='appendix',
            name='label',
            field=models.CharField(max_length=10, verbose_name='Буквенный индекс (А, Б, В...)'),
        ),
        migrations.AlterField(
            model_name='appendix',
            name='order',
            field=models.PositiveIntegerField(verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='appendix',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок приложения'),
        ),
        migrations.AlterField(
            model_name='bibliographyentry',
            name='entry_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Оформление по ГОСТ 7.1–2003'),
        ),
        migrations.AlterField(
            model_name='document',
            name='conclusion',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Заключение'),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='document',
            name='introduction',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Введение'),
        ),
        migrations.AlterField(
            model_name='document',
            name='main_part',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Основная часть'),
        ),
        migrations.AlterField(
            model_name='document',
            name='report_type',
            field=models.CharField(choices=[('final', 'Заключительный'), ('intermediate', 'Промежуточный')], default='intermediate', max_length=20, verbose_name='Тип отчета'),
        ),
        migrations.AlterField(
            model_name='document',
            name='template_type',
            field=models.CharField(choices=[('gost', 'ГОСТ 7.32'), ('sto', 'СТО СФУ 4.2')], max_length=10, verbose_name='Тип шаблона'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='document',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='document',
            name='year',
            field=models.PositiveIntegerField(default=2024, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='performer',
            name='date_signed',
            field=models.DateField(blank=True, null=True, verbose_name='Дата подписи'),
        ),
        migrations.AlterField(
            model_name='performer',
            name='degree',
            field=models.CharField(max_length=100, verbose_name='Ученая степень/звание'),
        ),
        migrations.AlterField(
            model_name='performer',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performers', to='documents.document', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='performer',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='performer',
            name='participation',
            field=models.CharField(blank=True, max_length=500, verbose_name='Участие / Вклад'),
        ),
        migrations.AlterField(
            model_name='performer',
            name='position',
            field=models.CharField(max_length=255, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='performer',
            name='signed',
            field=models.BooleanField(default=False, verbose_name='Подписано'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='citation',
            field=models.TextField(verbose_name='Описание источника (по ГОСТ)'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='documents.document', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='order',
            field=models.PositiveIntegerField(verbose_name='Порядок в списке'),
        ),
        migrations.AlterField(
            model_name='section',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержимое (HTML или текст)'),
        ),
        migrations.AlterField(
            model_name='term',
            name='definition',
            field=models.TextField(verbose_name='Определение'),
        ),
        migrations.AlterField(
            model_name='term',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='documents.document', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='term',
            name='term',
            field=models.CharField(max_length=255, verbose_name='Термин'),
        ),
        migrations.AlterField(
            model_name='titlepage',
            name='approval_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата утверждения'),
        ),
        migrations.AlterField(
            model_name='titlepage',
            name='book_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер книги (тома)'),
        ),
        migrations.AlterField(
            model_name='titlepage',
            name='department',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подразделение (отдел, кафедра)'),
        ),
        migrations.AlterField(
            model_name='titlepage',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='title_page', to='documents.document', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='titlepage',
            name='federal_program_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название фед. программы'),
        ),
        migrations.AlterField(
            model_name='titlepage',
            name='head_degree',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ученая степень руководителя'),
        ),
        migrations.AlterField(
            model_name='titlepage',
            name='head_full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО руководителя'),
        ),
        migrations.AlterField(
            model_name='titlepage',
            name='head_position',
            field=models.CharField(blank=True, max_length=255, verbose_name='Должность руководителя'),
        ),
        migrations.AlterField(
            model_name='titlepage',
            name='program_code',
            field=models.CharField(blank=True, max_length=255, verbose_name='Шифр программы'),
        ),
        migrations.AlterField(
            model_name='titlepage',
            name='registration_number_ikrbs',
            field=models.CharField(blank=True, max_length=100, verbose_name='Рег. номер ИКРБС'),
        ),
        migrations.AlterField(
            model_name='titlepage',
            name='registration_number_nioktr',
            field=models.CharField(blank=True, max_length=100, verbose_name='Рег. номер НИОКТР'),
        ),
        migrations.AlterField(
            model_name='titlepage',
            name='stage_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название этапа'),
        ),
        migrations.AlterField(
            model_name='titlepage',
            name='udk',
            field=models.CharField(blank=True, max_length=50, verbose_name='УДК'),
        ),
    ]
