# Generated by Django 5.2.1 on 2025-05-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_section_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='type',
            field=models.CharField(max_length=200, verbose_name='Тип раздела'),
        ),
    ]
