# Generated by Django 5.2.1 on 2025-05-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_section_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_sto',
            name='department_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Полное наименование кафедры'),
        ),
        migrations.AddField(
            model_name='document_sto',
            name='document_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название документа'),
        ),
        migrations.AddField(
            model_name='document_sto',
            name='institute_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Полное наименование института'),
        ),
        migrations.AddField(
            model_name='document_sto',
            name='university_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование университета'),
        ),
    ]
