# Generated by Django 5.2.1 on 2025-05-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_appendix_options_alter_document_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appendix_sto',
            name='content',
            field=models.TextField(verbose_name='Файл приложения'),
        ),
    ]
