# Generated by Django 5.2.1 on 2025-05-15 16:02

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_sto_department_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document_sto',
            name='owner',
        ),
        migrations.AlterField(
            model_name='document_sto',
            name='city',
            field=models.CharField(default='Москва', max_length=100, verbose_name='Город выполнения'),
        ),
        migrations.CreateModel(
            name='Document_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование университета')),
                ('institute_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Полное наименование института')),
                ('department_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Полное наименование кафедры')),
                ('document_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название документа')),
                ('work_type', models.CharField(choices=[('MAG_DIPLOMA', 'Магистерская диссертация'), ('DIPLOMA', 'Дипломная работа/проект'), ('BACHELOR', 'Бакалаврская работа'), ('COURSE', 'Курсовой проект/работа'), ('CALC_GRAPH', 'Расчётно-графическая работа'), ('PRACTICE', 'Отчёт по практике'), ('LAB', 'Отчёт по лабораторной работе'), ('REF', 'Реферат')], max_length=20, verbose_name='Вид работы')),
                ('specialty_code', models.CharField(blank=True, max_length=20, verbose_name='Код специальности')),
                ('specialty_name', models.CharField(blank=True, max_length=200, verbose_name='Наименование специальности/направления')),
                ('title', models.CharField(max_length=255, verbose_name='Тема работы')),
                ('supervisor', models.CharField(max_length=200, verbose_name='Руководитель (ФИО, ученая степень/звание)')),
                ('student_name', models.CharField(max_length=200, verbose_name='Исполнитель (ФИО)')),
                ('consultants', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='По пункту 6.2.2: консультанты и нормоконтролёр', verbose_name='Консультанты (ФИО, должность)')),
                ('approval_note', models.CharField(blank=True, help_text='Заполняется для ВКР и отчётов', max_length=200, verbose_name='Гриф утверждения')),
                ('city', models.CharField(default='Москва', max_length=100, verbose_name='Город выполнения')),
                ('year', models.PositiveSmallIntegerField(default=2025, verbose_name='Год выполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Все данные, которые будут отображаться в документе. \nРеферат: \nсодержание, \nвведение, \nосновная часть, \nзаключение, \nсписок использованных источников, \nприложения. \n', verbose_name='Данные')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Главный Документ',
                'verbose_name_plural': 'Главные Документы',
                'ordering': ['-created_at'],
            },
        ),
    ]
