# Generated by Django 5.2.1 on 2025-05-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_remove_document_sto_owner_alter_document_sto_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_main',
            name='stnadart',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Стандарт'),
        ),
    ]
