# Generated by Django 5.2.1 on 2025-05-15 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_main_stnadart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document_main',
            old_name='stnadart',
            new_name='standart',
        ),
    ]
